site_name: js-murph.github.io
site_description: A personal digital garden about technology and whatever else I feel like.
site_url: https://js-murph.github.io

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Games
        - Technology
        - Other
      pagination_per_page: 5
  - meta
  - tags
  - minify:
      minify_html: true
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

nav:
  - index.md
  - Blog:
    - blog/index.md
    - blog/tags.md